# Generated by Django 3.2 on 2021-04-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='qty',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
