# Generated by Django 3.2 on 2021-04-24 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0002_watch_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managment.category'),
        ),
    ]
